spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.8.157.61:3306/unite?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 10.8.157.61
    port: 6379
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  type-aliases-package: com.uniteproject.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 80


